image: continuumio/miniconda3

before_script:
  - apt-get update
  - apt-get install -y gcc tmux libxrender1

  - conda update -y -n base conda
  - conda install -c rdkit rdkit;\
  - conda install -c anaconda pygraphviz;\
  - conda install -c potassco clingo

  - pip install pathmodel pytest

test:python36:
  script:
  - pytest test/
