package:
  name: pathmodel
  version: "1.0.0"

source:
  git_url: https://gitlab.inria.fr/abelcour/PathModel.git

requirements:
  build:
    - python 3.6
    - setuptools
  run:
    - python 3.6
    - clingo=5.3.0
    - rdkit=2018.03.4.0
    - pygraphviz=1.3

test:
  imports:
    - pathmodel